language: java
jdk: oraclejdk8
before_install:
  - chmod a+x gradlew  
  - ./gradlew clean
install: ./gradlew setupCIWorkSpace
script: ./gradlew build
after_success: 
  - ./gradlew curseforge
  - ./gradlew bintrayUpload

notifications:
  email: false