package betterachievementsdemo.reference;

import net.minecraftforge.fml.common.ModMetadata;

import java.util.Arrays;

public class MetaData
{
    public static ModMetadata init(ModMetadata metadata)
    {
        metadata.modId = Reference.ID;
        metadata.name = Reference.NAME;
        metadata.description = "A demo of the features in BetterAchievements";
        metadata.url = "https://github.com/way2muchnoise/BetterAchievements";
        metadata.version = Reference.VERSION_FULL;
        metadata.authorList = Arrays.asList("way2muchnoise");
        metadata.credits = "";
        metadata.autogenerated = false;
        return metadata;
    }
}
